function [fitresult, gof] = accfit2(Afstand, V)
%CREATEFIT(AFSTAND,V)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : Afstand
%      Y Output: V
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-May-2015 14:41:31


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( Afstand, V );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [1.01039807695314 0.348428866856286 -1.03231482245784 -6.63920333438355];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'V vs. Afstand', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel Afstand
% ylabel V
% grid on


