function [fitresult, gof] = accfit(Afstand, V)
%CREATEFIT(AFSTAND,V)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : Afstand
%      Y Output: V
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-May-2015 14:27:23


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( Afstand, V );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.936811300797231;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'V vs. Afstand', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel Afstand
% ylabel V
% grid on


