function [fitresult, gof] = accfit_made_long(testafstand, V_test)
%CREATEFIT(TESTAFSTAND,V_TEST)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : testafstand
%      Y Output: V_test
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-May-2015 17:08:51


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( testafstand, V_test );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.Robust = 'LAR';
opts.StartPoint = [2.35379602627672 -1.3634663808658e-06 -2.5725402378154 -2.99830317298109];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'V_test vs. testafstand', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel testafstand
% ylabel V_test
% grid on

