function [fitresult, gof] = decfit(distance_d, velocity_d)
%CREATEFIT(DISTANCE_D,VELOCITY_D)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : distance_d
%      Y Output: velocity_d
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-May-2015 14:15:11


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( distance_d, velocity_d );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.946739270206915;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'velocity_d vs. distance_d', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel distance_d
% ylabel velocity_d
% grid on


