function [fitresult, gof] = decfit_fast(distance_d_fast, velocity_d_fast)
%CREATEFIT(DISTANCE_D_FAST,VELOCITY_D_FAST)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : distance_d_fast
%      Y Output: velocity_d_fast
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-May-2015 19:34:31


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( distance_d_fast, velocity_d_fast );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [-0.171070006756365 5.35071557686155 2.52837474534593 0.620078944125085];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'velocity_d_fast vs. distance_d_fast', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel distance_d_fast
% ylabel velocity_d_fast
% grid on


