function [fitresult, gof] = dist_time_acc(testtime, testafstand)
%CREATEFIT(TESTTIME,TESTAFSTAND)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : testtime
%      Y Output: testafstand
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-May-2015 20:49:04


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( testtime, testafstand );

% Set up fittype and options.
ft = 'linearinterp';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );
% 
% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'testafstand vs. testtime', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel testtime
% ylabel testafstand
% grid on


